words = [
    "alsa",
    "hifi",
    "htmx",
    "mousedown",
    "mpris",
    "mseconds",
    "qobuz",
    "qobuzissims",
    "reswap",
    "rfid",
    "subtab",
    "tera",
    "tracklist",
    "unstreamable",
]
